"""Typed event catalog for the event-driven core — the canonical taxonomy of bus events (MASTER_PLAN.md §4)."""

from enum import Enum


class Event(str, Enum):
    """Canonical event names published on the bus. Value == member name (str)."""

    PRICE_CROSS_LEVEL = "PRICE_CROSS_LEVEL"
    LEVEL_BREAK_CONFIRMED = "LEVEL_BREAK_CONFIRMED"
    SETUP_FORMING = "SETUP_FORMING"
    SETUP_CONFIRMED = "SETUP_CONFIRMED"
    SETUP_INVALIDATED = "SETUP_INVALIDATED"
    ORDER_INTENT = "ORDER_INTENT"
    ORDER_APPROVED = "ORDER_APPROVED"
    ORDER_VETOED = "ORDER_VETOED"
    ORDER_FILLED = "ORDER_FILLED"
    ORDER_PARTIAL = "ORDER_PARTIAL"
    ORDER_REJECTED = "ORDER_REJECTED"
    TP1_HIT = "TP1_HIT"
    STOP_HIT = "STOP_HIT"
    POSITION_CLOSED = "POSITION_CLOSED"
    CIRCUIT_BREAKER_TRIPPED = "CIRCUIT_BREAKER_TRIPPED"
    COOLDOWN_STARTED = "COOLDOWN_STARTED"
    NO_TRADE_WINDOW = "NO_TRADE_WINDOW"
    VOL_SPIKE = "VOL_SPIKE"
    DATA_ANOMALY = "DATA_ANOMALY"
    STRATEGY_DEMOTED = "STRATEGY_DEMOTED"
    MILESTONE_REACHED = "MILESTONE_REACHED"
    RATCHET_SWEEP = "RATCHET_SWEEP"
    DEPOSIT_LOGGED = "DEPOSIT_LOGGED"
    WATCHLIST_UPDATED = "WATCHLIST_UPDATED"
    SYMBOL_PROMOTED = "SYMBOL_PROMOTED"
    SYMBOL_DEMOTED = "SYMBOL_DEMOTED"
